### ISSUE TITLE
Serious error: spatial orientation ambiguous (tag 0020,0037 not found)

### ISSUE THREAD

**Issue by yarikoptic** [neurolabusc/dcm2niix#35] opened 2016-07-06 15:19 UTC
We are test-driving dcm2niix on sample files from soon-to-come Siemens Prisma 3T.  On some of them we get an 'error':

```shell
$> apt-cache policy dcm2niix
dcm2niix:
  Installed: 0.20160606.1+git1-gf6ba376-1~nd80+1
  Candidate: 0.20160606.1+git1-gf6ba376-1~nd80+1
  Version table:
 *** 0.20160606.1+git1-gf6ba376-1~nd80+1 0
        500 http://neuro.debian.net/debian/ jessie/main amd64 Packages
        100 /var/lib/dpkg/status

$> dcm2niix -b y -o NIfTIs2/ DICOMS/ABCD_DMRI_TENSOR_0017
Chris Rorden's dcm2niiX version 6June2016 (64-bit)
Found 1 DICOM image(s)
Serious error: spatial orientation ambiguous (tag 0020,0037 not found): DICOMS/ABCD_DMRI_TENSOR_0017/DARTMOUTH_PRISMA.MR.HEAD_ADVANCED_APPLICATIONS_LIBRARIES.0017.0001.2016.02.19.15.50.35.978090.98524631.IMA
No valid DICOM files were found
Conversion required 0.042988 seconds.
```

Here is 0020 fields and some nearby from dcmdump:

```
(0018,1020) LO [syngo MR E11]                           #  12, 1 SoftwareVersions
(0018,1030) LO [ABCD_dMRI]                              #  10, 1 ProtocolName
(0018,5100) CS [HFS]                                    #   4, 1 PatientPosition
(0020,000d) UI [1.3.12.2.1107.5.2.43.67026.30000016020614024824900000137] #  56, 1 StudyInstanceUID
(0020,000e) UI [1.3.12.2.1107.5.2.43.67026.2016021915224967228716830.0.0.0] #  58, 1 SeriesInstanceUID
(0020,0010) SH [1]                                      #   2, 1 StudyID
(0020,0011) IS [17]                                     #   2, 1 SeriesNumber
(0020,0012) IS [1]                                      #   2, 1 AcquisitionNumber
(0020,0013) IS [1]                                      #   2, 1 InstanceNumber
(0020,0052) UI [1.3.12.2.1107.5.2.43.67026.1.20160219145142005.0.0.0] #  52, 1 FrameOfReferenceUID
(0020,4000) LT [DTI Tensor]                             #  10, 1 ImageComments
(0029,0010) LO [SIEMENS CSA NON-IMAGE]                  #  22, 1 PrivateCreator
(0029,0011) LO [SIEMENS CSA HEADER]                     #  18, 1 PrivateCreator
(0029,0012) LO [SIEMENS MEDCOM HEADER2]                 #  22, 1 PrivateCreator
(0029,1008) CS [DTI NUM 4]                              #  10, 1 CSADataType
(0029,1009) LO [syngo MR E11]                           #  12, 1 CSADataVersion
(0029,1108) CS [DTI NUM 4]                              #  10, 1 CSAImageHeaderType
(0029,1109) LO [20160219]                               #   8, 1 CSAImageHeaderVersion
```

just for the record: another similar sequence which lead to similar error was `DICOMS/ABCD_DMRI_COLFA_0016`

**Comment by neurolabusc** [comment] 2016-07-06 16:48
I believe this is a duplicate of 
  http://www.nitrc.org/tracker/?func=detail&atid=3335&aid=8118&group_id=880
I think you tried to convert a derived image. In particular the file name "COLFA" probably refers to "COLOR RGB"

I think you should update to version 28June2016. If I am correct it will change the warning to the less shrill and more specific:
  Unable to determine spatial orientation: 0020,0037 missing (probably not a problem: derived image)
Explanation: I think this is a derived image (FA/ADC maps based on series of DWI scans) rather than a raw image. Be warned that Siemens does not preserve spatial coordinates when computing derived images. This is usually not an issue for scientists: the derived maps are stored in with very poor precision (8-bit RGB), most imaging software (FSL/SPM/AFNI) due not process RGB images. Furthermore, you can derive much nicer FA/ADC maps after you undistorted the raw images with Eddy/Topup.

Despite my clarified note to the user, I do still think this is a serious error. I do suggest you encourage Siemens to preserve the spatial encoding when generating derived images. No DICOM viewer will be able to determine spatial orientation without this. For example, if you drop one of these images on a tool popular with clinicians such as Osirix, they are not shown any labels for spatial orientation, so the user will have to know which is the left and right side of the brain.

**Closed** 2016-07-06 17:16 UTC

**Comment by yarikoptic** [comment] 2016-07-06 17:34
THANK YOU for the detailed explanation
